# citation:
# World Capital Cities
# Accessed on 5/18/24
# https://geographyfieldwork.com/WorldCapitalCities.htm


def country_requests(country):
    country = country.lower()
    print(country + "dictionary")
    country_capital = {
        "afghanistan": "Kabul",
        "albania": "Tirana(Tirane)",
        "algeria": "Algiers",
        "andorra": "Andorra la Vella",
        "angola": "Luanda",
        "antigua and Barbuda": "Saint John's",
        "argentina": "Buenos Aires",
        "armenia": "Yerevan",
        "australia": "Canberra",
        "austria": "Vienna",
        "azerbaijan": "Baku",
        "bahamas": "Nassau",
        "bahrain": "Manama",
        "bangladesh": "Dhaka",
        "barbados": "Bridgetown",
        "belarus": "Minsk",
        "belgium": "Brussels",
        "belize": "Belmopan",
        "benin": "Porto Novo",
        "bhutan": "Thimphu",
        "bolivia": "Sucre",
        "bosnia and herzegovina": "Sarajevo",
        "botswana": "Gaborone",
        "brazil": "Brasilia",
        "brunei": "Bandar Seri Begawan",
        "bulgaria": "Sofia",
        "burkina faso": "Ouagadougou",
        "burundi": "Gitega",
        "cambodia": "Phnom Penh",
        "cameroon": "Yaounde",
        "canada": "Ottawa",
        "cape verde": "Praia",
        "central african republic": "Bangui",
        "chad": "N'Djamena",
        "chile": "Santiago",
        "china": "Beijing",
        "colombia": "Bogota",
        "comoros": "Moroni",
        "democratic republic of the congo": "Kinshasa",
        "republic of the congo": "Brazzaville",
        "costa rica": "San Jose",
        "côte d 'ivoire": "Yamoussoukro",
        "croatia": "Zagreb:",
        "cuba": "Havana",
        "cyprus": "Nicosia",
        "czech republic": "Prague",
        "denmark": "Copenhagen",
        "djibouti": "Djibouti",
        "dominica": "Roseau",
        "dominican republic": "Santo Domingo",
        "east timor": "Dili",
        "ecuador": "Quito",
        "egypt": "Cairo",
        "el salvador": "San Salvador",
        "england": "London",
        "equatorial guinea": "Malabo",
        "eritrea": "Asmara",
        "estonia": "Tallinn",
        "eswatini": "Mbabane",
        "ethiopia": "Addis Ababa",
        "federated states of micronesia": "Palikir",
        "fiji": "Suva",
        "finland": "Helsinki",
        "france": "Paris",
        "gabon": "Libreville",
        "gambia": "Banjul",
        "georgia": "Tbilisi",
        "germany": "Berlin",
        "ghana": "Accra",
        "greece": "Athens",
        "grenada": "Saint George's",
        "guatemala": "Guatemala City",
        "guinea": "Conakry",
        "guinea - bissau": "Bissau",
        "guyana": "Georgetown",
        "haiti": "Port au Prince",
        "honduras": "Tegucigalpa",
        "hungary": "Budapest",
        "iceland": "Reykjavik",
        "india": "New Delhi",
        "indonesia": "Jakarta",
        "iran": "Tehran",
        "iraq": "baghdad",
        "ireland": "Dublin",
        "israel": "Jerusalem (very limited international recognition)",
        "italy": "Rome",
        "jamaica": "Kingston",
        "japan": "Tokyo",
        "jordan": "Amman",
        "kazakhstan": "Astana",
        "kenya": "Nairobi",
        "kiribati": "Tarawa Atoll",
        "Kosovo": "Pristina",
        "Kuwait": "Kuwait City",
        "kyrgyzstan": "Bishkek",
        "laos": "Vientiane",
        "latvia": "Riga",
        "lebanon": "Beirut",
        "lesotho": "Maseru",
        "liberia": "Monrovia",
        "libya": "Tripoli",
        "liechtenstein": "Vaduz",
        "lithuania": "Vilnius",
        "luxembourg": "Luxembourg",
        "madagascar": "Antananarivo",
        "malawi": "Lilongwe",
        "malaysia": "Kuala Lumpur",
        "maldives": "Male",
        "mali": "Bamako",
        "malta": "Valletta",
        "marshall islands": "Majuro",
        "mauritania": "Nouakchott",
        "mauritius": "Port Louis",
        "mexico": "Mexico City",
        "moldova": "Chisinau",
        "monaco": "Monaco",
        "mongolia": "Ulaanbaatar",
        "montenegro": "Podgorica",
        "morocco": "Rabat",
        "mozambique": "Maputo",
        "myanmar(burma)": "Nay Pyi Taw",
        "namibia": "Windhoek",
        "nauru": "No official capital",
        "nepal": "Kathmandu",
        "netherlands": "Amsterdam",
        "new zealand": "Wellington",
        "nicaragua": "Managua",
        "niger": "Niamey",
        "nigeria": "Abuja",
        "north korea": "Pyongyang",
        "north macedonia": "Skopje",
        "northern ireland": "Belfast",
        "norway": "Oslo",
        "oman": "Muscat",
        "pakistan": "Islamabad",
        "palau": "Melekeok",
        "palestine": "Jerusalem(very limited international recognition)",
        "panama": "Panama City",
        "papua new guinea": "Port Moresby",
        "paraguay": "Asuncion",
        "peru": "Lima",
        "philippines": "Manila",
        "poland": "Warsaw",
        "portugal": "Lisbon",
        "qatar": "Doha",
        "romania": "Bucharest",
        "russia": "Moscow",
        "rwanda": "Kigali",
        "saint kitts and nevis": "Basseterre",
        "saint lucia": "Castries",
        "saint vincent and the grenadines": "Kingstown",
        "samoa": "Apia",
        "san marino": "San Marino",
        "sao tome and principe": "Sao Tome",
        "saudi arabia": "Riyadh",
        "scotland": "Edinburgh",
        "senegal": "Dakar",
        "serbia": "Belgrade",
        "seychelles": "Victoria",
        "sierra leone": "Freetown",
        "singapore": "Singapore",
        "slovakia": "Bratislava",
        "slovenia": "Ljubljana",
        "solomon islands": "Honiara",
        "somalia": "mogadishu",
        "south africa": "Pretoria, Bloemfontein, Cape Town",
        "south korea": "Seoul",
        "south sudan": "Juba",
        "spain": "Madrid",
        "sri lanka": "Sri Jayawardenapura Kotte",
        "sudan": "Khartoum",
        "suriname": "Paramaribo",
        "sweden": "Stockholm",
        "switzerland": "Bern",
        "syria": "Damascus",
        "taiwan": "Taipei",
        "tajikistan": "Dushanbe",
        "tanzania": "Dodoma",
        "thailand": "Bangkok",
        "togo": "Lome",
        "tonga": "Nuku'alofa",
        "trinidad and tobago": "Port of Spain",
        "tunisia": "Tunis",
        "turkey": "Ankara",
        "turkmenistan": "Ashgabat",
        "tuvalu": "Funafuti",
        "uganda": "Kampala",
        "ukraine": "Kyiv or Kiev",
        "united arab emirates": "Abu Dhabi",
        "united kingdom": "London",
        "united states": "Washington D.C.",
        "uruguay": "Montevideo",
        "uzbekistan": "Tashkent",
        "vanuatu": "Port Vila",
        "vatican city": "Vatican City",
        "venezuela": "Caracas",
        "vietnam": "Hanoi",
        "wales": "Cardiff",
        "yemen": "Sana'a",
        "zambia": "Lusaka",
        "zimbabwe": "Harare"
    }

    if country not in country_capital:
        return "Country not listed, please try again"
    else:
        capital = country_capital.get(country)
        return capital
